// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO-w_jimTFUfrwBcI-98QgAP7teTQBYlw',
    appId: '1:143198019955:web:698a959c575707cebfa506',
    messagingSenderId: '143198019955',
    projectId: 'flutter-weather-app-ffac1',
    authDomain: 'flutter-weather-app-ffac1.firebaseapp.com',
    storageBucket: 'flutter-weather-app-ffac1.appspot.com',
    measurementId: 'G-SPQY3CTPCH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDszUg9nVByUaoZLf_Okpg9ysR3aWYAzH8',
    appId: '1:143198019955:android:4e48d244d23180aebfa506',
    messagingSenderId: '143198019955',
    projectId: 'flutter-weather-app-ffac1',
    storageBucket: 'flutter-weather-app-ffac1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWbYZZ-s7O0094WaKMPq7CTKUL27s7LVI',
    appId: '1:143198019955:ios:84e1c97b31d876a5bfa506',
    messagingSenderId: '143198019955',
    projectId: 'flutter-weather-app-ffac1',
    storageBucket: 'flutter-weather-app-ffac1.appspot.com',
    iosClientId: '143198019955-87p8fve1f4kpkaghr154fkibsu8lk5eh.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterWeatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWbYZZ-s7O0094WaKMPq7CTKUL27s7LVI',
    appId: '1:143198019955:ios:f7346d980ed3555fbfa506',
    messagingSenderId: '143198019955',
    projectId: 'flutter-weather-app-ffac1',
    storageBucket: 'flutter-weather-app-ffac1.appspot.com',
    iosClientId: '143198019955-fmto31d8ujpn88q1oii1mlnr313gl5q6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterWeatherApp.RunnerTests',
  );
}
